apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mtasst-titansim
  labels:
    app.kubernetes.io/name: "mtas-st-chart-titansim"
    helm.sh/chart: {{ include "mtas-st-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "mtas-st-chart-titansim"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "mtas-st-chart-titansim"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: sekilxc1236
        image: "{{ .Values.titansimImage.repository }}:{{ .Values.titansimImage.tag }}"
        imagePullPolicy: {{ .Values.titansimImage.pullPolicy }}
        tty: true
        stdin_open: true
        env:
        - name: http_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
        - name: https_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - name: ssh
          containerPort: 22
          targetPort: 22
          protocol: TCP
        hostname: sekilxc1236
      nodeSelector:
        type: titansim
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mtasst-sending
  labels:
    app.kubernetes.io/name: "mtas-st-chart-sending"
    helm.sh/chart: {{ include "mtas-st-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "mtas-st-chart-sending"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "mtas-st-chart-sending"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: sekilxc1234
        image: "{{ .Values.sendingImage.repository }}:{{ .Values.sendingImage.tag }}"
        imagePullPolicy: {{ .Values.sendingImage.pullPolicy }}
        tty: true
        stdin_open: true
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - name: ssh
          containerPort: 22
          targetPort: 22
          protocol: TCP
        env:
        - name: http_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
        - name: https_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
      hostname: sekilxc1234
      nodeSelector:
        type: sender
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mtasst-receiving
  labels:
    app.kubernetes.io/name: "mtas-st-chart-receiving"
    helm.sh/chart: {{ include "mtas-st-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "mtas-st-chart-receiving"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "mtas-st-chart-receiving"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: sekilxc1235
        image: "{{ .Values.receivingImage.repository }}:{{ .Values.receivingImage.tag }}"
        imagePullPolicy: {{ .Values.receivingImage.pullPolicy }}
        tty: true
        stdin_open: true
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - name: ssh
          containerPort: 22
          targetPort: 22
          protocol: TCP
        env:
        - name: http_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
        - name: https_proxy
          value: http://inet-proxy.k2.ericsson.se:8080
      hostname: sekilxc1235
      nodeSelector: ### node selector changes working
        type: receiver
