apiVersion: v1
kind: Service
metadata:
  name: sekilxc1235
  labels:
    app.kubernetes.io/name: "mtas-st-chart-reciving"
    #    app.kubernetes.io/name: {{ include "mtas-st-chart.name" . }}
    helm.sh/chart: {{ include "mtas-st-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
        #  type: {{ .Values.service.type }}
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
    - targetPort: 14558
      port: 14558
      nodePort: 14558
      name: sipp14558
    - targetPort: 14559
      port: 14559
      nodePort: 14559
      name: sipp14559
    - targetPort: 5666
      port: 5666
      nodePort: 5666
      name: tcp5666
  selector:
    app.kubernetes.io/name: "mtas-st-chart-receiving"
    #    app.kubernetes.io/name: {{ include "mtas-st-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
