apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mtasst-receiving
  labels:
    app.kubernetes.io/name: "mtas-st-chart-receiving"
    #    app.kubernetes.io/name: {{ include "mtas-st-chart.name" . }}
    helm.sh/chart: {{ include "mtas-st-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    #app.kubernetes.io/instance: re-mtas-system-test
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "mtas-st-chart-receiving"
      #      app.kubernetes.io/name: {{ include "mtas-st-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "mtas-st-chart-receiving"
        #        app.kubernetes.io/name: {{ include "mtas-st-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: sekilxc1236
          image: "{{ .Values.receivingImage.repository }}:{{ .Values.receivingImage.tag }}"
          imagePullPolicy: {{ .Values.receivingImage.pullPolicy }}
          tty: true
          stdin_open: true
          #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - name: ssh
              containerPort: 22
              targetPort: 22
              protocol: TCP
              #livenessProbe:
              #httpGet:
              #path: /
              #port: http
              #readinessProbe:
              #httpGet:
              #path: /
              #port: http
          hostname: sekilxc1236
          volumes:
            - name: "receiving-volume"
              mountPath: "/st"

      nodeSelector: ### node selector changes working
        type: receiver
